### ISSUE TITLE
Questions abount the pratical performance of the released checkpoints

### ISSUE THREAD

**Issue by Ferry-Li** [sjtuplayer/few-shot-diffusion#11]
Hi! This work is inspiring and impressive! It is so nice of you to release the code for research.
However, I encountered some problems when using the released checkpoints. I downloaded them from [target-domain diffusion model](https://drive.google.com/drive/folders/1luEH2SrETjj5rfZcmIxibhwBVBNA5S8F?usp=sharing) and tried to run the generate.py with 
`python generate.py --ckpt_path ckpt/target_domain/ffhq_to_cartoon.pth --img_path source_img --save_path generations/cartoon`
where I put some pngs into the dir `source_img` from the ffhq dataset. 
The output image is confusing: 
![0.png](https://github.com/sjtuplayer/few-shot-diffusion/assets/65407659/ef08fb29-1ae9-44e5-b2ae-15dc8a436554)
and I hardly find the "cartoon" style. 
Are there some mistakes when I generate the cartoon-styled images?

**Comment by sjtuplayer** [comment]
How about other styles like sketch?

**Comment by Ferry-Li** [comment]
> How about other styles like sketch?

The outputs of the three styles (cartoon, sketch, and Vangogh) are similar as displayed above. Speicifically, 
sketch: 
![sketch.png](https://github.com/sjtuplayer/few-shot-diffusion/assets/65407659/3e2cddd1-6f13-4bd5-8189-8b754e7ae8c1)
Vangogh:
![Vangogh.png](https://github.com/sjtuplayer/few-shot-diffusion/assets/65407659/c6d9f25f-1a9a-4458-a6f3-a970976408bc)

**Comment by sjtuplayer** [comment]
> > How about other styles like sketch?
> 
> The outputs of the three styles (cartoon, sketch, and Vangogh) are similar as displayed above. Speicifically, sketch: ![sketch.png](https://private-user-images.githubusercontent.com/65407659/329764031-3e2cddd1-6f13-4bd5-8189-8b754e7ae8c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTU0NDMsIm5iZiI6MTcxNTQxNTE0MywicGF0aCI6Ii82NTQwNzY1OS8zMjk3NjQwMzEtM2UyY2RkZDEtNmYxMy00YmQ1LTgxODktOGI3NTRlN2FlOGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4MTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzQ5NTc2ZTdlYzRkNjIwYzYzYjlhODJkNTY0Yjg0ZTFmZTE5OGY0MjIxNWQ3MWIxNTgyNTU2NTNkOTMxOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cb4WOF5vhMcMwZdqOfI8veFHCDhIgAfEmnJ6OW_uaLo) Vangogh: ![Vangogh.png](https://private-user-images.githubusercontent.com/65407659/329764066-c6d9f25f-1a9a-4458-a6f3-a970976408bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTU0NDMsIm5iZiI6MTcxNTQxNTE0MywicGF0aCI6Ii82NTQwNzY1OS8zMjk3NjQwNjYtYzZkOWYyNWYtMWE5YS00NDU4LWE2ZjMtYTk3MDk3NjQwOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA4MTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZTAxZWIyMjA5OGI0MjU4ZTg3ZDBkODBmYzAzMWVlMjI0MTg2ODRiNTA4NTdkMTAzMzEwYzFiNWI2NTkzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fg5ooi8UY-wWWEc7ROZ85enV7tTXJA0xtNRvrgyJSLI)

Maybe you can check the version of denoising_diffusion_pytorch? Is it 0.28.0? We have rechecked the code and checkpoints, there is no problem when we run it.

**Comment by Ferry-Li** [comment]
Thank you very much! I checked my version and re-install the 0.28.0. It works.

Thanks again for your help and your amazing work!
