### ISSUE TITLE
Question with train-recon.py

### ISSUE THREAD

**Issue by JubSteven** [sjtuplayer/few-shot-diffusion#2]
Hi, I have an question with train-recon.py. In the README file, it is said that we need to provide a path for checkpoints (presumably the result of stage 1 using train.py), but I don't seem to find the code in train-recon.py for actually **using** the checkpoints, and directly running the scripts appears to train from the beginning. Can you help clarify the issue? Thanks!

**Comment by JubSteven** [comment]
> Hi, I have rewritten the code for stages 2 and 3, you can now easily train the model.

Thanks! But I have encoutered a new problem trying to load the ckpt from stage 2 to stage3, as it gives the following err (matching issue). I have used the generated ckpts from stage 2 for the --ckpt option in stage3. 

<img width="849" alt="1701932148898" src="https://github.com/sjtuplayer/few-shot-diffusion/assets/95260261/26adbbec-7f83-430b-9cca-77e301857111">

**Comment by sjtuplayer** [comment]
If you use the pre-trained diffusion model on the source domain, a single 24G GPU is enough to adapt the model from source domain to target domain (step 2 and 3). For step 1, we have used 8 V100 GPUs to train.

**Comment by sjtuplayer** [comment]
> > Hi, I have rewritten the code for stages 2 and 3, you can now easily train the model.
> 
> Thanks! May I ask what is the GPU requirement for this task?

If you use the pre-trained diffusion model on the source domain, a single 24G GPU is enough to adapt the model from source domain to target domain (step 2 and 3). For step 1, we have used 8 V100 GPUs to train.

**Comment by JubSteven** [comment]
OK, thanks for your patience!
