### ISSUE TITLE
download link for source dataset and target dataset

### ISSUE THREAD

**Issue by fikry102** [sjtuplayer/few-shot-diffusion#3]
> And we translate the model to the target domain: (1) Sketches [32], (2) Cartoon [25], (3) Paintings by Van Gogh [38] and (4) Haunted houses [24]. The experiments are conducted in both 10-shot and 5-shot settings.

Could you please the download link for target dataset **in both 10-shot and 5-shot setting**s?

**Comment by sjtuplayer** [comment]
The link has been updated in readme: https://drive.google.com/drive/folders/1VAJU5yEolmd2xAIUI7xvGNaHKBs4B7QX

**Comment by fikry102** [comment]
> The link has been updated in readme: https://drive.google.com/drive/folders/1VAJU5yEolmd2xAIUI7xvGNaHKBs4B7Q

Which images are used for 5-shot? There are 10 images under the shared folder.

**Comment by sjtuplayer** [comment]
> > The link has been updated in readme: https://drive.google.com/drive/folders/1VAJU5yEolmd2xAIUI7xvGNaHKBs4B7Q
> 
> Which images are used for 5-shot? There are 10 images under the shared folder.
you can use the 5 images with the lowest ID number as the 5-shot data.

**Comment by sjtuplayer** [comment]
> > The link has been updated in readme: https://drive.google.com/drive/folders/1VAJU5yEolmd2xAIUI7xvGNaHKBs4B7Q
> 
> Which images are used for 5-shot? There are 10 images under the shared folder.

you can use the 5 images with the lowest ID number as the 5-shot data.
